### ISSUE TITLE
App stops reacting to ‘off’ commands

### ISSUE THREAD

**Issue by rogierhofboer** [rogierhofboer/com.ikea.tradfri.gateway#1]
After running for a few days, the app stops responding to turn light off or to light on commands. Dimming still works, also the lights still respond correctly when using the Tradfri Android app. Needs to be investigated.
I cannot produce this by operating the lights / running flows. Maybe it is due to a loss a connection with the Tradfri gateway which is not restored correctly. 

(Also maybe related is: https://forum.iobroker.net/viewtopic.php?t=12379)

**Comment by mmwolbrink** [comment]
My lights statuses don't update in the app when they are controlled from another source than homey. I guess that that is because of this bug ?
Is the app still in active development by the way ?

**Comment by rogierhofboer** [comment]
@mmwolbrink The status of the lights should be updated in the App, also if they controlled by the IKEA App or a physicial remote. I have to check this at home, but this used to work on my setup. If it worked first, but then stopped working after a few days of operation, it could be because of this bug. 

At the moment I am not working on the app. I still need to investigate this issue (some day) and will try to get the App to beta status after that. Pull requests are welcome and I will review them as soon as possible.

**Comment by mmwolbrink** [comment]
@rogierhofboer As far as i now it has never worked for me.

**Comment by rogierhofboer** [comment]
Tested last night, works at my home. Interesting... I use the old non-beta Homey smartphone app, I remember the beta App doesn’t do status updates at all.

**Comment by nnameihtd** [comment]
@rogierhofboer How Can I test this app on my Homey? On the Homey Commnity Forum I read that you can assign people to the Alpha-list. Is that still possible? Thanks in advance for your reply.

**Comment by rogierhofboer** [comment]
@nnameihtd you can send me an email (from or with email you use to login on your homey) and I will add you as alpha tester.

It seems the problems I experience (no on/off)are only present on older versions of the homey firmware and the losing of the login keys others mentioned are solved in the last firmware update. So my plan is to upgrade my homey, do a quick test and try to get the app accepted for beta by athom.

**Comment by nnameihtd** [comment]
Beste Rogier,

Dank voor je reactie. Mijn emailadres dion.thiemann@gmail.com
Hiermee ben ik ook bij Homey geregistreerd.
Hopelijk komt deze email aan.

Dank!

Dion


Op vrijdag 19 oktober 2018 heeft rogierhofboer <notifications@github.com>
het volgende geschreven:

**Comment by rogierhofboer** [comment]
An email is ok use rogier at hofboer dot nl

**Comment by rogierhofboer** [comment]
Unfortunately this bug is still present when using Homey firmware 1.5.12

My best guess is the Homey app and the Tradfri gateway get out-of-sync, because of a temporary Wifi network failure. So the homey misses an update. It cannot be reproduced by temporary disconnecting the Tradfri gateway, because after reconnecting everything is synced.
It also explains why it can take multiple days for the problems to surface and (most?) other people do not seem to have it at all.

**Comment by rogierhofboer** [comment]
using a different wifi access point solves this problem for me. Still I think it will get out of sync if the connection is bad. Detecting this can be difficult. Reconnecting always restores the situation in working order.

This is most probably behaviour of the underlying node-tradfri-client library.

**Comment by Daverp123** [comment]
I left home today, with working homey app and lights. From the neighbours the Homey app would not responds to the light requests I make.  When I returned the Homey older app still did not work.  Tradfri app works fine.   Also the Homey app was able to move the Somfy blinds from same range next door.

What can I do next about this Homey and Ikea lighting control issue?  

Resetting hardware and reinstalling app and skill works as fix this time...  but I'm not willing to do this often or use the Flows which in turn fail, which in turn makes Homey useless for many.

**Comment by rogierhofboer** [comment]
If this is the same problem..

Make sure there are no wifi interruptions (controlling things will work, but it gets out of sync after short wifi hiccups)

To fix do one of these:

- restart the tradfri gateway app.
- click connect in the tradfri gateway app settings
- restart the tradfri gateway (PtP)
- restart Homey (PtP)

**Comment by rogierhofboer** [comment]
I have not experienced this problem anymore. Might be due to better Wifi. Closing for now.
