### ISSUE TITLE
Discover error

### ISSUE THREAD

**Issue by markussandin1** [rogierhofboer/com.ikea.tradfri.gateway#11]
When I try to discover the Ikea Gateway I just get an error message. I have tried re-install it a couple of times.

**Comment by markussandin1** [comment]
![646c12d8-4b1b-426d-ba2b-03fa43240e29](https://user-images.githubusercontent.com/19946298/48088053-3e211400-e201-11e8-9a8b-e3a5fc65247c.png)

**Comment by markussandin1** [comment]
Update: after filling in the IP and security code, the app provides credentials for identity and psk. But when saving I get settings saved and error pop ups over each other.

**Comment by rogierhofboer** [comment]
Hi, what version of the homey firmware are you using? It seems there are troubles with 1.5.13rc11.

**Comment by markussandin1** [comment]
1.5.12

**Comment by rogierhofboer** [comment]
ok. Thanks. To be honest, I have no idea at the moment why you have this problem.
I am thinking about adding logging to the app, in such a way you can share this with me, but only after consent. But this will not be soon. The only thing I can suggest right now is to re-install the app and to try again. Also if you didn't do so, use the Homey Desktop app, instead the beta of the new app or the web-browser.

**Comment by markussandin1** [comment]
Ok, i will try the desktop version.

**Comment by markussandin1** [comment]
I tried the mac desktop version and it worked! Thank you.
