### ISSUE TITLE
Add support for TRADFRI on/off Switch

### ISSUE THREAD

**Issue by mikkie123** [rogierhofboer/com.ikea.tradfri.gateway#12]
Would it be possible to add support for the on/off Switch, related to the Outlet Plug ?

**Comment by rogierhofboer** [comment]
The switches are not (yet?) supported as separate devices to receive events from. So at the moment is not possible to add them.

**Comment by rogierhofboer** [comment]
I will add support for the remotes / switches if this situation changes
