### ISSUE TITLE
Non-responsive Hub

### ISSUE THREAD

**Issue by Astra707** [rogierhofboer/com.ikea.tradfri.gateway#13]
Since version 0.0.9 the Ikea Tradfri hub is becoming unresponsive every three to four days. If I disable the app, it seems to keep working. Problem didn't occur with 0.0.4. Is it just me..?

**Comment by mickeman** [comment]
Hi! 
I just wanted to say that i have never experienced this problem.
Have used the app since it came out in april.
I am using it to control my trådfri lamps with 433mhz wall switches through homey.
And a few sun related flows to control window lights.
Have never had the other problem either that the appmaker has.
[https://github.com/rogierhofboer/com.ikea.tradfri.gateway/issues/1](url)
Running app ver 0.0.9 and Homey 1.5.12 and i have an old Unifi UAP (Firmware 3.9.49.9260) that homey connects to.
(In case this is wifi related)

**Comment by rogierhofboer** [comment]
Yes I recognise this. For me dimming still works in this case, only switching stops working (sometimes I cannot switch on anymore, sonetimes not off anymore)

**Comment by rogierhofboer** [comment]
I now have Google Home mini. Even this device sometimes doesn't switches all the lights via the Tradfri gateway. A Gateway restart helps in this case. Also this seems to at least temporary solve the issue were lights flicker once shortly after being turned on via mains power (so you have a regular switch still connected, you turn the lamp on, and after 1 to 2 seconds the light goes off and on again very fast)

For my app if it doesn't respond anymore in the correct way (issue #1), it also helps to go to the settings and press save.

For now it seems that keeping a session for a long time can make this session unstable on the gateway and in might have something to do with the wifi quality. 

But I haven't seen a fully unstable gateway like you are describing.

**Comment by rogierhofboer** [comment]
Let me also check if there is something between 0.0.8 and 0.0.9 that might cause this issue.

**Comment by Astra707** [comment]
I've done some additional testing, new flows etc, but can't reproduce the problem... It has been stable for almost two weeks now..? I also have a Google Home mini, will see how that affects stability of the hub. (could off course also be something within the hub, instead of the app).

**Comment by rogierhofboer** [comment]
ok good to hear. For me when using google home to switch all lights, not all of them always go on or off, it seems Google Home and the tradfri gateway can get out of sync.
This seems a known problem.
https://www.reddit.com/r/tradfri/comments/a3axka/bulb_wont_turn_off/eb4uvaz/?context=3

**Comment by rogierhofboer** [comment]
I am closing the issue, because in general it did occur anymore.
Still there is a problem of lights getting out-of-sync (also with Google home), but this covered by issue #1
