### ISSUE TITLE
Can't add Ikea Gateway

### ISSUE THREAD

**Issue by HampusHaak** [rogierhofboer/com.ikea.tradfri.gateway#15]
After upgrading to 2.0 all the lights stopped working and I get an error trying to config the gateway with the security code, 

Error: An unknown error has occured [invalid_json] 

![Error](https://imgur.com/a/23DqB5i)

**Comment by HampusHaak** [comment]
https://imgur.com/a/23DqB5i

**Comment by rogierhofboer** [comment]
I am very sorry, but the configuration only works from the desktop App. I believe it is removed in 2.0. I will not upgrade my Homey  until 2.0 is stable for a while. In the mean time I will look if there is any info on how to make settings work for 2.0

**Comment by HampusHaak** [comment]
Okey Thanks for your work

**Comment by rogierhofboer** [comment]
@HampusHaak It seems it is also was already broken in 1.5.13 I've made a fix that solved the problem for 1.5.13. The version is 0.0.10 alpha. Can you test with Homey 2.0.x ? If you are not already an alpha tester, please drop me a mail (or message via slack) with the email address you use for your athom account.

**Comment by rogierhofboer** [comment]
Got 4 reports the problem is solved (2x on 1.5.13 and 2x on 2.0.x). Closing issue.
