### ISSUE TITLE
if not working homey v2

### ISSUE THREAD

**Issue by AlbertDijksma** [rogierhofboer/com.ikea.tradfri.gateway#16]
Hi Rogier.
if ikealicht1 switched on then .....  is not working after homey update to v2.
i use this in a flow to contol non ikea lights when my ikea light is switched on

**Comment by AlbertDijksma** [comment]
Hi Rogier.
Problem is fixed with homey update rc3

**Comment by rogierhofboer** [comment]
Ok thanks for reporting. I will close the issue.
