### ISSUE TITLE
Lights stay in 'home' zone

### ISSUE THREAD

**Issue by Jovink** [rogierhofboer/com.ikea.tradfri.gateway#17]
Hi,
When I make a flow the lights are still in the home zone. 
I have set them to bedroom and on the device tab they are visible in that room but when I create a flow the are still in the home zone.
![20181217_232001](https://user-images.githubusercontent.com/16411340/50119433-12a73580-0253-11e9-898c-8255d81fed4d.jpg)
![20181217_231926](https://user-images.githubusercontent.com/16411340/50119449-1aff7080-0253-11e9-9ad1-f2625364f9f5.jpg)

**Comment by rogierhofboer** [comment]
The app doesn’t keep zones / names of the Ikea app and homey in sync (yet).
If this all happens within the Homey app, this might also be a Homey bug.

**Comment by Jovink** [comment]
I know the bulbs don't get the zone's from the ikea app. But had set the zone's in the homey app. 
I did a ptp and the issue is solved, however if I make a flow with turn off the lights in a zone the lights won't go off.

**Comment by rogierhofboer** [comment]
Hi @Jovink,

Do you still experience this problem?
Is it only present with ikea tradfri gateway app or are you able to reproduce it with other devices (i.g. the Sonos speakers)?

Which Homey firmware version do you use?

**Comment by Jovink** [comment]
Hi,
No I don't have any problems with the app. You can close this issue.

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
