### ISSUE TITLE
tradfri Plug isn't working

### ISSUE THREAD

**Issue by janpi80** [rogierhofboer/com.ikea.tradfri.gateway#18]
Hi, thanks for this nice solution. For some reason the wallplug doesn't work. All other lamps work. deleting and adding didn't work. the tradfri app does work.

**Comment by rogierhofboer** [comment]
Hi @janpi80,

Could you provide more information?
Which Homey firmware version do you use?
Are you able to add the plug at all? Or does operating it not work? Do you try to use it from a group or as device?

I do have a wall plug and it works. Also others reported they have plugs which work, so I need a little more details to find out why it doesn‘t work for you ;)

**Comment by rogierhofboer** [comment]
I am not sure if I can update the state to unavailable, but will look into it.
Also the old app showed devices that were turned off as unavailable, but the preview app doesn't. Don't know for 2.0 yet, since I am still on 1.5.13

Closing this issue.
