### ISSUE TITLE
App does not work after Homey reboot

### ISSUE THREAD

**Issue by json81** [rogierhofboer/com.ikea.tradfri.gateway#21]
Homey 2.0.2 (problem was present in all 2.0 versions up to current version).

**Problem:** IKEA Trådfri Gateway doesn't work after Homey reboot. Trådfri app works.
**How to reproduce:** reboot Homey.
**Solution:** In Homey, go to the IKEA Trådfri Gateway-app and click the save button (no need to change settings).

**Comment by rogierhofboer** [comment]
Seems it is not ready yet to connect just after reboot. It should retry, but this also doesn't seem to work for you.
Unfortunately I am not able to test or reproduce this, since I am still on 1.5.13.
Pull requests are welcome though...

**Comment by json81** [comment]
Thanks for your feedback. 

I think I have found my problem. It is one of the bulb that is causing this behavior. If I remove the device from Trådfri Gateway I can reboot again and the connection to the gateway works without re-saving the settings . I will do some more research with this bulb and let you know the result.

**Comment by json81** [comment]
Update: I have done some more testing with this particular bulb and it is not related to the problem. Problem seems to be intermittent and I think it is network related. Would it be possible to delay the connection retry to fix this problem?

**Comment by mickeman** [comment]
Hi, also got this problem now. (Unable to control Ikea Gateway after reboot)
I have found out that if homey is connected to my newly installed Unifi AC Lite i cannot control
my trådfri gateway from homey.
Restarting app or re-saving settings helps, until homey is rebooted.
Tried with 5ghz disabled in the AC-lite but that did not help.
Tried a few different firmwares on the AC-lite too. (didn´t help)
After much testing i found out that if i connect Homey to my old Unifi UAP v1 (2.4ghz only) 
the problem is solved.
Now i can reboot homey and the trådfri gateway app works directly. (Have rebooted av few times without problem)
I am running on beta firmware on both AP´s ver 4.0.21.9965 and homey is 2.0
Some kind of auto reconnect or maybe delay before starting the app after reboot could solve this?

**Comment by json81** [comment]
Hi,
Then we have something in common. I am using Homey 2.0.2 and UniFi AC-LR. I have just updated the firmware on AC-LR to latest stable (4.0.15). After the update I could reboot Homey and stay connected to Trådfri Gateway without problems (3 reboots). I just tried to reboot again when I saw your post and it failed. I have been running the same APs for the last year so no change there. My problems started after updated to Homey 2.0. I am running the UniFi app on Homey (that connects to UniFi Controller) without any problems (do not need to reconnect after reboot).

**Comment by rogierhofboer** [comment]
I think this is the same issue as #25

**Comment by rogierhofboer** [comment]
I am now on firmware 2.04 and I am also experiencing this problem now.

There should be no need to re-enter the security code (issue #25). 
Just go to settings and save the current settings (again).
What also helps is to restart the Tradfri gateway app.

I will try look into this in the coming days.

**Comment by Gizmopower1** [comment]
After restart of Homey it looses its security code.
Type it in and save, and its ok again

**Comment by rogierhofboer** [comment]
What Homey firmware version are you using?
Here at 2.1.2 this doesn't happen. I restarted Homey yesterday by pulling
the plug (moved it to use a different wall socket)

Op vr 24 mei 2019 om 12:27 schreef Gizmopower1 <notifications@github.com>:

**Comment by Gizmopower1** [comment]
It has been like this for some versions 

I just updated to 2.2.0 rc7 
Still the same...

**Comment by proisland** [comment]
I have the same issue every time I reboot the Homey. I have tried restarting the app, and pressing save in app settings without the issue going away. I always need to put in the security code before the app starts working again.

**Comment by json81** [comment]
Same problem with Homey v.2.5.2 and IKEA Trådfri Gateway v.0.0.11. I need to push save-button in the app after I have restarted Homey.

**Comment by frostih** [comment]
Is there any solution to this problem?  It's still like this on my Homey (v.3).  I restart it every night and therefore I always need to submit the security code every morning.   As much as I love this app, this is frustrating.

**Comment by C0kedk** [comment]
> Is there any solution to this problem? It's still like this on my Homey (v.3). I restart it every night and therefore I always need to submit the security code every morning. As much as I love this app, this is frustrating.

just restart the ikea Gateway app via a flow, set it after 30 mins the homey reboots.

this works without having to resubmit security code.

**Comment by rogierhofboer** [comment]
Does this still happen with the latest (v0.1.0) version?

**Comment by C0kedk** [comment]
Yea

**Comment by torroa** [comment]
Any updates on this?

**Comment by proisland** [comment]
Still happens here as well. Every since I installed the first version of this app.

**Comment by torroa** [comment]
The updated v0.1.2 on jan. 16 seems to have fixed the connection to the gateway when Homey reboot.

Thank you for taking your time fixing this rogierhofboer. Just hoping that the "unknown error" does not re-appear. Any chance that increasing memory usage can be prevented? It starts at 12mb but quickly increase to 40mb if the app is not restarted. Memory spikes is not something the Homey is particularly found of as it only got 512 of them...

**Comment by json81** [comment]
Closes this case now. Fixed in version 0.1.2.
