### ISSUE TITLE
'Set relative dim-level' calculates wrong.

### ISSUE THREAD

**Issue by Genghes** [rogierhofboer/com.ikea.tradfri.gateway#22]
If i have a dim level of 80% (0.8) and set relativ dim-level to -50% the dimlevel becomes 30%. This means it's just subtracting 50 from 80.. I would think -50% should meen 50% og the current level (80%-50%=40%).

If the dimlevel is 40% and the relative dim level is -50%, the dimlevel becomes 0 and the light turns off. It should dim to 50% of the current level.

**Comment by slasktrat** [comment]
Sorry, but the calculation is not wrong. Relative dim is built-in functionality in Homey and designed to work just like you say it does. Use case is e.g. if you have a button or rotating dimmer where you'd like to dim in steps, etc.

**Comment by Genghes** [comment]
OK, thanks for the quick answer.
