### ISSUE TITLE
Devices not working after homey update 2.0rc4

### ISSUE THREAD

**Issue by Sannieslief** [rogierhofboer/com.ikea.tradfri.gateway#24]
Ikea tradfri not working. Lamps wont respond. Diagnostic report. 1d20aad4-7b5d-4d34-ad7a-0e9fb1203e60

**Comment by rogierhofboer** [comment]
Do you still experience this issue with Homey firmware 2.04 or later?

**Comment by Sannieslief** [comment]
Problem is fixed. Thanks!

Verstuurd vanaf mijn iPhone
