### ISSUE TITLE
Security code

### ISSUE THREAD

**Issue by rpbras** [rogierhofboer/com.ikea.tradfri.gateway#25]
Is it normal that I sometimes have to fill in the security code again? Espacially when Homey restarted?
Thnx in advance for any answer.

Kind regards,
Raymond

**Comment by proisland** [comment]
I have the same issue. Its very annoying. Hope it can be fixed soon.

**Comment by rogierhofboer** [comment]
Yes, this happens since Homey 2.x 
I've just upgraded to Homey 2.0 myself and will look into this issue.

**Comment by rogierhofboer** [comment]
Closing as duplicate (no further reaction received)
