### ISSUE TITLE
Group light - light temperature (hue) - Homey v2.02

### ISSUE THREAD

**Issue by camiri96** [rogierhofboer/com.ikea.tradfri.gateway#26]
Adding same type of light-bulbs (with color temperature controls) as a Group only give three options for light temperature (Focus, Everyday, Relax), compared to a sliding scale option of 0 to 1 if the bulbs are added standalone as Light. This yield less options, and make algorithmic changes impossible.

v0.0.11 Homey 2.02

**Comment by rogierhofboer** [comment]
When using groups, you can only select scenes and turn on/off and dim the group.
It is not possible to set the light temperature for a group. See also the underlying library I am using:
https://github.com/AlCalzone/node-tradfri-client#group

For more fine grained control, use individual lights and create "groups" using Homey flows.
