### ISSUE TITLE
Group light - light color - Homey v2.02

### ISSUE THREAD

**Issue by camiri96** [rogierhofboer/com.ikea.tradfri.gateway#27]
When adding color lights as a Group, even if the bulbs are of the same type (color can change), they loose the option to change the color in the 0-1 scale (options available when added as standalone lights). Only 5 mood options remains (Focus, Sunset, Relax, Everyday, Sun). The bulbs looses the color options, and algorithmic changes to color using number variables cannot be done. The option for Random color is also absent when added as Group, but there if each bulb is added standalone.

v0.0.11 Homey v2.02

**Comment by rogierhofboer** [comment]
This is not possible via the API of the gateway. When using groups, you can only select scenes, dim all lights and turn on/off. See also https://github.com/AlCalzone/node-tradfri-client#group
