### ISSUE TITLE
Error when configuring gateway 

### ISSUE THREAD

**Issue by jwilmenius** [rogierhofboer/com.ikea.tradfri.gateway#28]
Hi,

Suddenly stopped working and tried to reinstall. Now I get an error setting up after adding the gateway security code... 

Error: the gateway did not respond in time

Could it be because an ikea GW update? Running 1.4.15

Thanks for a great up, really want it back! :)

/Johan

**Comment by rogierhofboer** [comment]
Hi Johan,

There was no update of the IKEA gateway.
1.4.15 is already rolled out for months.
Maybe Athom did an update?

I am still on Homey 1.5.13 and have no plan to update anytime soon...(waiting for things to get more stable)

**Comment by jwilmenius** [comment]
Hi.

It seems my router panicked causing the slowdown and the problem. After reboot everything works great again!

Sorry for not figuring this out before...

Best regards!

/Johan

24 feb. 2019 kl. 21:59 skrev rogierhofboer <notifications@github.com<mailto:notifications@github.com>>:


Hi Johan,

There was no update of the IKEA gateway.
1.4.15 is already rolled out for months.
Maybe Athom did an update?

I am still on Homey 1.5.13 and have no plan to update anytime soon...(waiting for things to get more stable)

**Comment by rogierhofboer** [comment]
Ok :)  I will close this issue.
