### ISSUE TITLE
Unknown_error when turning on the lights

### ISSUE THREAD

**Issue by mhoogenbosch** [rogierhofboer/com.ikea.tradfri.gateway#32]
I often get a message within the Homey app, there is a "Unknown_error" when turning on the lights. Doesn't matter if it's a group or just a single light.

The full message in Dutch is: "Er ging iets fout, probeer het later opnieuw. (Er is een onbekende fout opgetreden [unknown_error]).

I've got my IKEA Gateway on a fixed IP and also tried to pair the connection a second time. Everything connects just fine. When I get this error I can still control the lights with the IKEA app itself. After restarting your app on homey it starts working again. 

I kind of managed to work around this problem by restarting the app every 15 minutes, but even then I often have the lights not being turned off after sunrise because of this error.

Is there a way to troubleshoot this?

**Comment by ralfh73** [comment]
Same issue here. 2 times this week already.
When I checked the IKEA tradfri app, all devices where gone.
Restarted the IKEA bridge, IKEA app showed all devices. In homey re-entered the security code. Then restarted app and finally it works again.

**Comment by torroa** [comment]
Same issue here. Homey v3.1.1 and Gateway app v0.1.0

After some time of inactivity, the app or Homey stops communicating with the Gateway. Only solution is to restart the app.

The solution I am using until this is fixed, is to use a flow that repeats every 30 minutes telling a bulb to change the colour temperature to 95%. Not very elegant, but it keeps the communication between the app and the gateway alive.

**Comment by ralfh73** [comment]
Thanks torroa,
It seems to work so far. I have some additional questions:
- some people on the homey-forum also restart their homey in the night. Do you do that too ?
- How did you come up with the 30 minutes ? Could I also extend that to 1 hour ?

**Comment by torroa** [comment]
When I restart Homey I have to enter the IKEA Trådfri Gateway settings and press [Save] for it to communicate with the Trådfri hub. If not I get the similar message "Something went wrong. Please try again". I tried to restart homey every night, but ended up with unresponsive lights every morning.

I have had the Homey for a few weeks, but when I am unable to include my z-wave lock or my IKEA hub, Homey will be returned next week.

**Comment by rogierhofboer** [comment]
Hi, the crash reports I receive all have to do with groups / scenes. Do you use those?

 I had disconnecting problems with homey to the IKEA gateway on a UPC connect box, then switched to a TP Link C7 and the disconnecting problem went away.

The homey tradfri gateway app is a wrapper around node-tradfri-client, I will have to look into that library again to see if it can be fixed there.

**Comment by torroa** [comment]
Thank you for the feedback rogierhofboer. I have not added any groups, nor any scenes activated on either the IKEA hub on Homey.

I have removed the IKEA hub integration with HomeKit and Google Assistant. I included a group when I first installed the app. I have no idea if any of those settings are still stored on my Homey.

I have a few Apple Airports around the house, and all devises have reserved IP adresses. I have not tried to uninstall the app or reset the Homey to factory settings - mainly because of the PITA it would be to recreate all the flows, and if it still doesn't work, I would hate Homey even more :P

**Comment by ralfh73** [comment]
@rogierhofboer I have 2 groups in the Tradfri-app. I target that group from the homey app.

**Comment by torroa** [comment]
I think I might have located the source of the "unknown_error" at my home.  

Som other users mentioned that they have connected the IKEA hub to a different router and that the problem disappeared.  I tried that and moved the IKEA hub from the Inteno router that my broadband company provided to an Apple Airport Extreme. Both in bridge mode used as wired access points. And now, know on woods, the gateway app has been working flawlessly for nearly 24 hours. Previously, I would get the Unknown_error if I did not adjust any lights each half hour or so.

**Comment by ralfh73** [comment]
@torroa unfortunately I don't have the chance to connect another router.
I suspect that any setting in the router could cure this problem. Maybe related to keeping a stream alive or an energy setting.
I might have a look at that, but for now the 30-minute-wakeup-call is my workaround that does it. ;-)

**Comment by C0kedk** [comment]
i got zero probs on 4 homeys / ikea gateways (all asus routers).

Once a week the power for the ikea gateway must be cut, allways restart the app in homey afterwards.

-static ip is ofc. essential!

**Comment by rogierhofboer** [comment]
No recent updates, seems network relalated. Closing for now. Feel free reopen.
