### ISSUE TITLE
New version of node-tradfri-client, supporting the blinds

### ISSUE THREAD

**Issue by mhoogenbosch** [rogierhofboer/com.ikea.tradfri.gateway#33]
Don't even know if you still support this app, but there is a new version of node-tradfri-client which supports the blinds. Thought you might wanted to know.

**Comment by C0kedk** [comment]
Please @Rogierhofboer update the node, please ! 🙏🙏

**Comment by lvhv91** [comment]
node-tradfri-client is updated to the latest version.

**Comment by C0kedk** [comment]
> node-tradfri-client is updated to the latest version.
👍
How do i get "your" version ? 🙂

**Comment by mhoogenbosch** [comment]
> > node-tradfri-client is updated to the latest version.
> > 👍
> > How do i get "your" version ? 🙂

Download zip and install through CLI. I can add the 'rolgordijn', just have to find time to do so. Maybe this weekend ;-)

**Comment by mhoogenbosch** [comment]
I'll close the issue, thanks a lot, lads!

**Comment by lvhv91** [comment]
For manually installing the app follow the instructions on https://community.athom.com/t/how-to-cli-install-method/198. The blinds are available on the master branch (https://github.com/rogierhofboer/com.ikea.tradfri.gateway/archive/master.zip).

**Comment by C0kedk** [comment]
@lvhv91 
Works flawless, thank you so much for this ! 👍
