### ISSUE TITLE
App won’t start anymore

### ISSUE THREAD

**Issue by GrimmJok3r** [rogierhofboer/com.ikea.tradfri.gateway#34]
Hi Rogier,

Thx for the great all.
Unfortunately a view weeks ago I had an issue controlling my ikea devices trough homey and when I tried restarting The app got an error.
After rebooting homey multiple times still nothing.
At a certain point the app crashed and it wasn’t able to start anymore, even after reinstalling the app still nothing it just keeps showing the loading button in the apps overview. I have generated a report

4b6273b7-287f-418e-82fb-03da51506b8b

Thx in advance
Regards
Thijs

**Comment by rogierhofboer** [comment]
Hi Thijs,

At the moment I am not using the gateway myself (switched to Deconz).

It seems the last few Homey updates made things worse for the app, not sure what's going on. Getting these reports it seems it went from fully stable to needing a restart every 15 minutes. 
Pull requests to fix this are welcome, and I might look into it myself if no-one else has the knowledge and time to do it...

**Comment by GrimmJok3r** [comment]
Hoi Rogier,

Doe het wel ff in NL :)
Dank voor je antwoord, spijtig dat hij idd niet meer stabiel is.
Jij bent helemaal overgestapt naar Deconz?
Ben ook andere opties aan het bekijken dan Homey
Heb nu praktisch alles thuis vervangen zodat alles via te bedienen is met Homey maar merk dat die het niet meer red, hij is traag aan het worden.
Zat te kijken naar die pro maar vind hem eerlijk gezegd te duur voor wat je er voor krijgt en ben bang dat ik die ook snel aan zn max heb ( zeker als ik naar Mn huidige geheugens gebruik kijk.

Ben me dus een beetje aan het oriënteren. :)

Thx
Thijs

Sent from the nether regions

On 16 Sep 2019, at 00:16, rogierhofboer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Thijs,

At the moment I am not using the gateway myself (switched to Deconz).

It seems the last few Homey updates made things worse for the app, not sure what's going on. Getting these reports it seems it went from fully stable to needing a restart every 15 minutes.
Pull requests to fix this are welcome, and I might look into it myself if no-one else has the knowledge and time to do it...

**Comment by rogierhofboer** [comment]
Hoi Thijs,

Github issues zijn niet zo handig (en bedoeld) om hierover te chatten. 
Stuur me even persoonlijk berichtje via de homey slack of een directe email met je voorkeursmanier van communiceren bv Telegram/Skype/Whatsapp. 
Groetjes Rogier

**Comment by GrimmJok3r** [comment]
Removed my other comment ;)
Problem seems to be solved for now
Problem was that Homey had issues with the IKEA gateway app and after a lot of trying it wouldn’t start any more
Strangely enough a lot more app started to fail in the same manner.
Restarted homey a couple of times but nothing seem to help
After physically unplugging homey’s Psu and booting it up again all problems where gone like they never existed
Homey got its speed back and all worked well again
So reboot doesn’t help but power cycling does

Thank you
