### ISSUE TITLE
Auto add additional color scenes

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [rogierhofboer/com.ikea.tradfri.gateway#39]
In the Ikea app I can create additional scenes (Sferen in Dutch).
In Homey we can only choose the default three scenes.

![2019-11-15 21 34 32](https://user-images.githubusercontent.com/28575285/68975326-3ff9bc00-07f3-11ea-9d4a-e59f2d25c1ca.png)

**Comment by MP-ICT-Diensten** [comment]
Inspiration can be found in the node-red tradfri hub module.

https://github.com/xopr/node-red-contrib-node-tradfri

**Comment by rogierhofboer** [comment]
I've never used nor did the development of the group / scene support for this app. It was added via a pull request. It might be the scenes are not synchronised anymore after the first addition of the group to the homey app. You could try if removing a group with more scenes (moods) and re-adding it helps in this case. Of course it is still a good feature request to add this synchronisation.

**Comment by rogierhofboer** [comment]
This functionality is replaced by Scenes, added in v0.1.3 of this app. Closing for now.
