### ISSUE TITLE
Adding the possibility to chose the defined colors

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [rogierhofboer/com.ikea.tradfri.gateway#40]
In Homey the possibility to choose the colors for a lamp.

![2019-11-15 21 35 02](https://user-images.githubusercontent.com/28575285/68975385-6a4b7980-07f3-11ea-8e95-9d447a9c2e5a.png)

**Comment by MP-ICT-Diensten** [comment]
Inspiration can be found in the node-red tradfri hub module.

https://github.com/xopr/node-red-contrib-node-tradfri

**Comment by rogierhofboer** [comment]
This not something an app can control. This should be asked to Athom.
