### ISSUE TITLE
Received fatal alert

### ISSUE THREAD

**Issue by Raycokes2000** [rogierhofboer/com.ikea.tradfri.gateway#47]
Hello, 
![Screenshot_20200527_112632_app homey](https://user-images.githubusercontent.com/51300944/83003169-3e187d00-a00e-11ea-9da2-601df4c613db.jpg)
See attachment, Received fatal alert on led spot. What to with that?
Gr Ray

**Comment by rogierhofboer** [comment]
I am not sure if it is related to your issue. But I am receiving a lot of crash logs saying the node_aead_crypto library cannot be found. It seems to be a corrupted installation in a way....

**Comment by Raycokes2000** [comment]
OK, damn, that did the trick again 🤦‍♀️
It generally steps, have you turned it off En on again. Reloaded software, re installed? 80% problems solved with those steps, 🤔😋🤣🤣🤞😎

**Comment by Raycokes2000** [comment]
Closed and thanks
