### ISSUE TITLE
Please add new device Tradfri Square Dimmer

### ISSUE THREAD

**Issue by klim123123** [rogierhofboer/com.ikea.tradfri.gateway#48]
Please add device Tradfri Square Dimmer aka 004.684.32 aka Tradfri On/Off switch.
I can connect it to Ikea hub, but not possible to add in plugin.

**Comment by rogierhofboer** [comment]
The dimmer, remote and switches are not directly exposed by the IKEA Tradfri gateway.
If you want to use them directly, you could switch to Deconz ( https://homey.app/nl-nl/app/de.dresden-elektronik.deconz/deCONZ/) or Zigbee2Mqtt (https://homey.app/nl-nl/app/nl.scanno.mqtt/MQTT-Client/)
and maybe the new Zigbee binding in Homey v5 will support them.
