### ISSUE TITLE
Add support to TRADFRI control outlet

### ISSUE THREAD

**Issue by mickeman** [rogierhofboer/com.ikea.tradfri.gateway#5]
Could you please add support to the new TRADFRI control outlet.
![ikea-smartplug](https://user-images.githubusercontent.com/37731791/45585013-a3c9e180-b8dd-11e8-8bdc-784fdc994dd0.jpg)

**Comment by rogierhofboer** [comment]
I will try to add support soon after they become available in The Netherlands.

**Comment by Astra707** [comment]
Really happy with your project on my Homey, stable as a rock! The sockets are available now, can't wait  for the support in your app. ;-)

Do you have a timeline when this app is generally available on Homey? I think a lot of people would be very happy with that. 

And last but not least, if I can help (translating, as in your timeline), no problem!

**Comment by rogierhofboer** [comment]
The app is now in beta.
Better group support is added to the latest alpha.
Support for sockets will be added this weekend to alpha.

**Comment by Astra707** [comment]
Great! When will the app be updated in the athom app store?

**Comment by talzac** [comment]
Where can I find and install the alpha version ?

**Comment by rogierhofboer** [comment]
See issue #3 :)

**Comment by rogierhofboer** [comment]
Included from version 0.0.8
