### ISSUE TITLE
After install app for the first time, not able to configure app (no instructions, and discover only gives error)

### ISSUE THREAD

**Issue by wfdekker** [rogierhofboer/com.ikea.tradfri.gateway#59]
I can't seem to be able to get the app configured. I put in the correct ip address and security code but app keeps saying "error".
Also no idea where I should find the PSK...

Help

**Comment by wfdekker** [comment]
Hmmm, in parallel to making this issue also restarted Homey. That fixed it... but instructions somewhere how to do this (and that PSK is auto filled in etc), would still be useful

**Comment by rogierhofboer** [comment]
In v0.1.5 the settings are better clarified. Closing this issue for now.
