### ISSUE TITLE
Seems like after update on IKEA Gateway to 1.15.34 it is not working anymore.

### ISSUE THREAD

**Issue by Gizmopower1** [rogierhofboer/com.ikea.tradfri.gateway#62]
Seems like after update on IKEA Gateway to 1.15.34 it is not working with homey anymore.
Cant connect. Gateway not responding error 
-Error: The gateway did not respond in time.-

V1.15.34 Ikea gateway
V0.1.4 på Ikea Gateway app in Homey
V7.0.1-rc.5 Software på Homey

**Comment by hendrik607** [comment]
Same here, have same version, do not see this version in Ikea app releases........ strange......

**Comment by jtebbens** [comment]
Yeah also problems here after firmware update as per 30th june

**Comment by marcel1334** [comment]
Unfortunately same over here. Tried reboot of gateway and homey, but this did not solve the problem. I hope it can be easily fixed. Thanks in advance.

**Comment by habiben** [comment]
Same for me. "The gateway did not respond in time"

**Comment by rogierhofboer** [comment]
This is because of a bug in the DTLS protoco implementationl of this tradfri firmware update. See also: https://github.com/AlCalzone/node-tradfri-client/issues/517. There is a workaround implemented in node-tradfri-client. Updating to the latest version should fix the problem.

**Comment by hendrik607** [comment]
There is a workaround implemented in node-tradfri-client.............. is this updating the Tradfri app on Homey ?

**Comment by Gizmopower1** [comment]
Will the com.ikea.tradfri.gateway be updated with this fix? If not, how and what do we update?

**Comment by rogierhofboer** [comment]
Should be fixed now with update of node-tradfri-client.

**Comment by hendrik607** [comment]
works again, thanks!
