### ISSUE TITLE
Compatibility with Homey Cloud

### ISSUE THREAD

**Issue by chimpinwetsuit** [rogierhofboer/com.ikea.tradfri.gateway#67]
This is a feature request. I missed this app after joining the Homey (Cloud) beta.
How-to information here:
https://apps.developer.homey.app/guides/homey-cloud

**Comment by rogierhofboer** [comment]
Homey cloud (bridge) can't do any local network traffic. 
The Ikea Tradfri gateway can only reached via the local network. 
The only way to make it cloud compatible is to use another device like a Google Home, Alexa.
(assuming homey cloud is not meant for Homey Pro or Home Asssistant / OpenHAB users)
But when controlling the gateway via another integration, this app is not needed.

Please correct me if I misunderstood how Homey Cloud works.
