### ISSUE TITLE
Compatibility with Homey Pro (Early 2023) (SDK V3)

### ISSUE THREAD

**Issue by Sceptic666** [rogierhofboer/com.ikea.tradfri.gateway#69]
Is there any plan to make this app compatible with Homey Pro (Early 2023)?

**Comment by HenkRenting** [comment]
Yes, an update to SDK3 would be very welcome because of the upcomimg Homey Pro 2023! :) I'd be happy to support you, @rogierhofboer!

**Comment by kikkerX10** [comment]
@rogierhofboer ,
Hi Rogier, can you please inform us about your plan for the upgrade to sdk3?
At this moment i get the feeling that I wil be left in the dark. Almost every light in my house is running on the great ikea tradfri app

**Comment by HenkRenting** [comment]
See
https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/942
The current developer want to see (quite some) money first...

**Comment by rogierhofboer** [comment]
Money is not the problem. 

I don't use the Tradfri gateway myself at the moment. 

And I have already another hobby-project besides, my normal day job taking up much time.

So I don't make any promises about when I will look at this.

Pull requests or even a project takeover are therefore welcome.

**Comment by HenkRenting** [comment]
I referred to the app in the Homey App Store.
But when you are the developer of the Github app, I suppose this is another app than the one in the Homey App Store?


________________________________

**Comment by rogierhofboer** [comment]
You've posted a link to the Xiaomi app, this repository contains the Ikea Tradfri Gateway app.
I am not the author of the Xiaomi app.

**Comment by HenkRenting** [comment]
Ok, clear. Thx. :)
But that author wants to see money first before an SDK 3 updated app is released,. So money is an issue for him I'm afraid... See the url I posted before.


________________________________

**Comment by rogierhofboer** [comment]
FYI: I've received a pull request from @slasktrat which I intend to review before Monday February 13

**Comment by HenkRenting** [comment]
Oops, sorry! I completely overlooked the part where this is  ot the Xiaomi bit Tradfri Gateway app.
Damn, how stupid. My sincere apologies!

Leaves the fact that I do use the Ikea Gateway app as well and would be very pleased if this one could be updated to SDK3/Homey 2023 as well.
So thanks for your effort!
I"d be happy to support you wherever I can.

**Comment by kikkerX10** [comment]
Yes! Let there be light! Ikea light! Via the Tradfri Hub for the comming 2 to 3 years (end of support for Tradfri hub probably).

It is great to hear that someone is willing to take a look at the app!

**Comment by kikkerX10** [comment]
Any news regarding the review of the pull request by slasktrat

**Comment by rogierhofboer** [comment]
Yes, an updated version is published to test , you can try it out here. If there are no big issues I will ask for a review by Athom.
https://homey.app/a/com.ikea.tradfri.gateway/test/
