### ISSUE TITLE
Can the new IKEA Dirigera be supported as well?

### ISSUE THREAD

**Issue by Rummuter** [rogierhofboer/com.ikea.tradfri.gateway#70]
With IKEA changing to another hub, can this be added to this particular app, or perhaps as a separate app?
There is useable information in this link.
https://github.com/dvdgeisler/DirigeraClient

**Comment by rogierhofboer** [comment]
I don't have a Dirigera Hub at the moment and I have no intention to buy one,
IMHO it should be a separate app, because the API seems totally different from the Tradfri gateway.
