### ISSUE TITLE
Difference from official Athom app

### ISSUE THREAD

**Issue by antonhagg** [rogierhofboer/com.ikea.tradfri.gateway#91]
Noticed that there is also an official app from Athom. What exactly is the difference?

**Comment by rogierhofboer** [comment]
The Athom app uses the Zigbee radio of the Homey to communicate directly with the Tradfri devices.
This app communicates with the Ikea Tradfri gateway, which then communicates via its own Zigbee radio with the Tradfri devices.

Using the Tradfri gateway has the benefit it can do firmware updates and the remotes fully work out of the box, including scene (color/light temperature) switching, but you cannot use the remotes to control other devices. Also there will be 2 Zigbee Networks, taking up more of the 2.4Ghz space.

By connecting directly using the Athom app, the devices do not get firmware updates and a flow needs to be created for every remote button action, but you can also use the remotes to control other devices and there will be only one Zigbee network.


If you want the best of both worlds and maximum control, I'd recommend using Zigbee2MQTT on a separate device (e.g. Raspberry Pi) using a Zigbee USB stick) as Zigbee gateway. There is an MQTT client for Homey and also a Hub if you don't run an MQTT Hub elsewhere (for example on the Raspberry Pi).

**Comment by antonhagg** [comment]
Nice, thanks for this clarification.

**Comment by antonhagg** [comment]
Maybe it should be in the read me. 😊
